// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: agent/toolplugin/pb/plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_agent_toolplugin_pb_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescriptionResponse) Reset() {
	*x = DescriptionResponse{}
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescriptionResponse) ProtoMessage() {}

func (x *DescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescriptionResponse.ProtoReflect.Descriptor instead.
func (*DescriptionResponse) Descriptor() ([]byte, []int) {
	return file_agent_toolplugin_pb_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *DescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ToolProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // JSON Schema type: string, integer, boolean, array, object
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Items         *ToolProperty          `protobuf:"bytes,5,opt,name=items,proto3" json:"items,omitempty"`
	Properties    []*ToolProperty        `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolProperty) Reset() {
	*x = ToolProperty{}
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolProperty) ProtoMessage() {}

func (x *ToolProperty) ProtoReflect() protoreflect.Message {
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolProperty.ProtoReflect.Descriptor instead.
func (*ToolProperty) Descriptor() ([]byte, []int) {
	return file_agent_toolplugin_pb_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ToolProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolProperty) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolProperty) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ToolProperty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolProperty) GetItems() *ToolProperty {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ToolProperty) GetProperties() []*ToolProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

type PropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    []*ToolProperty        `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertiesResponse) Reset() {
	*x = PropertiesResponse{}
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertiesResponse) ProtoMessage() {}

func (x *PropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertiesResponse.ProtoReflect.Descriptor instead.
func (*PropertiesResponse) Descriptor() ([]byte, []int) {
	return file_agent_toolplugin_pb_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PropertiesResponse) GetProperties() []*ToolProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctxmeta       *structpb.Struct       `protobuf:"bytes,1,opt,name=ctxmeta,proto3" json:"ctxmeta,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_agent_toolplugin_pb_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetCtxmeta() *structpb.Struct {
	if x != nil {
		return x.Ctxmeta
	}
	return nil
}

func (x *ExecuteRequest) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ImageURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageURL) Reset() {
	*x = ImageURL{}
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageURL) ProtoMessage() {}

func (x *ImageURL) ProtoReflect() protoreflect.Message {
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageURL.ProtoReflect.Descriptor instead.
func (*ImageURL) Descriptor() ([]byte, []int) {
	return file_agent_toolplugin_pb_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ImageURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageURL) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type BinaryImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MimeType      string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"` // image/png, image/jpeg, image/webp
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryImage) Reset() {
	*x = BinaryImage{}
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryImage) ProtoMessage() {}

func (x *BinaryImage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryImage.ProtoReflect.Descriptor instead.
func (*BinaryImage) Descriptor() ([]byte, []int) {
	return file_agent_toolplugin_pb_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *BinaryImage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *BinaryImage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImagePart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ImagePart_ImageUrl
	//	*ImagePart_Binary
	Content       isImagePart_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePart) Reset() {
	*x = ImagePart{}
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePart) ProtoMessage() {}

func (x *ImagePart) ProtoReflect() protoreflect.Message {
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePart.ProtoReflect.Descriptor instead.
func (*ImagePart) Descriptor() ([]byte, []int) {
	return file_agent_toolplugin_pb_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ImagePart) GetContent() isImagePart_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ImagePart) GetImageUrl() *ImageURL {
	if x != nil {
		if x, ok := x.Content.(*ImagePart_ImageUrl); ok {
			return x.ImageUrl
		}
	}
	return nil
}

func (x *ImagePart) GetBinary() *BinaryImage {
	if x != nil {
		if x, ok := x.Content.(*ImagePart_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

type isImagePart_Content interface {
	isImagePart_Content()
}

type ImagePart_ImageUrl struct {
	ImageUrl *ImageURL `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

type ImagePart_Binary struct {
	Binary *BinaryImage `protobuf:"bytes,2,opt,name=binary,proto3,oneof"`
}

func (*ImagePart_ImageUrl) isImagePart_Content() {}

func (*ImagePart_Binary) isImagePart_Content() {}

type ExecuteResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Result            string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	StructuredContent *structpb.Struct       `protobuf:"bytes,2,opt,name=structured_content,json=structuredContent,proto3" json:"structured_content,omitempty"`
	ImageParts        []*ImagePart           `protobuf:"bytes,3,rep,name=image_parts,json=imageParts,proto3" json:"image_parts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_toolplugin_pb_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_agent_toolplugin_pb_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecuteResponse) GetStructuredContent() *structpb.Struct {
	if x != nil {
		return x.StructuredContent
	}
	return nil
}

func (x *ExecuteResponse) GetImageParts() []*ImagePart {
	if x != nil {
		return x.ImageParts
	}
	return nil
}

var File_agent_toolplugin_pb_plugin_proto protoreflect.FileDescriptor

const file_agent_toolplugin_pb_plugin_proto_rawDesc = "" +
	"\n" +
	" agent/toolplugin/pb/plugin.proto\x12\x06plugin\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x13DescriptionResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"\xd6\x01\n" +
	"\fToolProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12*\n" +
	"\x05items\x18\x05 \x01(\v2\x14.plugin.ToolPropertyR\x05items\x124\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2\x14.plugin.ToolPropertyR\n" +
	"properties\"J\n" +
	"\x12PropertiesResponse\x124\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2\x14.plugin.ToolPropertyR\n" +
	"properties\"|\n" +
	"\x0eExecuteRequest\x121\n" +
	"\actxmeta\x18\x01 \x01(\v2\x17.google.protobuf.StructR\actxmeta\x127\n" +
	"\n" +
	"parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"4\n" +
	"\bImageURL\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\">\n" +
	"\vBinaryImage\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"v\n" +
	"\tImagePart\x12/\n" +
	"\timage_url\x18\x01 \x01(\v2\x10.plugin.ImageURLH\x00R\bimageUrl\x12-\n" +
	"\x06binary\x18\x02 \x01(\v2\x13.plugin.BinaryImageH\x00R\x06binaryB\t\n" +
	"\acontent\"\xa5\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12F\n" +
	"\x12structured_content\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x11structuredContent\x122\n" +
	"\vimage_parts\x18\x03 \x03(\v2\x11.plugin.ImagePartR\n" +
	"imageParts2\x83\x03\n" +
	"\rPluginService\x128\n" +
	"\x04Init\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x126\n" +
	"\x04Name\x12\x16.google.protobuf.Empty\x1a\x14.plugin.NameResponse\"\x00\x12D\n" +
	"\vDescription\x12\x16.google.protobuf.Empty\x1a\x1b.plugin.DescriptionResponse\"\x00\x12B\n" +
	"\n" +
	"Properties\x12\x16.google.protobuf.Empty\x1a\x1a.plugin.PropertiesResponse\"\x00\x12<\n" +
	"\aExecute\x12\x16.plugin.ExecuteRequest\x1a\x17.plugin.ExecuteResponse\"\x00\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B\x06Z\x04.;pbb\x06proto3"

var (
	file_agent_toolplugin_pb_plugin_proto_rawDescOnce sync.Once
	file_agent_toolplugin_pb_plugin_proto_rawDescData []byte
)

func file_agent_toolplugin_pb_plugin_proto_rawDescGZIP() []byte {
	file_agent_toolplugin_pb_plugin_proto_rawDescOnce.Do(func() {
		file_agent_toolplugin_pb_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_toolplugin_pb_plugin_proto_rawDesc), len(file_agent_toolplugin_pb_plugin_proto_rawDesc)))
	})
	return file_agent_toolplugin_pb_plugin_proto_rawDescData
}

var file_agent_toolplugin_pb_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_agent_toolplugin_pb_plugin_proto_goTypes = []any{
	(*NameResponse)(nil),        // 0: plugin.NameResponse
	(*DescriptionResponse)(nil), // 1: plugin.DescriptionResponse
	(*ToolProperty)(nil),        // 2: plugin.ToolProperty
	(*PropertiesResponse)(nil),  // 3: plugin.PropertiesResponse
	(*ExecuteRequest)(nil),      // 4: plugin.ExecuteRequest
	(*ImageURL)(nil),            // 5: plugin.ImageURL
	(*BinaryImage)(nil),         // 6: plugin.BinaryImage
	(*ImagePart)(nil),           // 7: plugin.ImagePart
	(*ExecuteResponse)(nil),     // 8: plugin.ExecuteResponse
	(*structpb.Struct)(nil),     // 9: google.protobuf.Struct
	(*emptypb.Empty)(nil),       // 10: google.protobuf.Empty
}
var file_agent_toolplugin_pb_plugin_proto_depIdxs = []int32{
	2,  // 0: plugin.ToolProperty.items:type_name -> plugin.ToolProperty
	2,  // 1: plugin.ToolProperty.properties:type_name -> plugin.ToolProperty
	2,  // 2: plugin.PropertiesResponse.properties:type_name -> plugin.ToolProperty
	9,  // 3: plugin.ExecuteRequest.ctxmeta:type_name -> google.protobuf.Struct
	9,  // 4: plugin.ExecuteRequest.parameters:type_name -> google.protobuf.Struct
	5,  // 5: plugin.ImagePart.image_url:type_name -> plugin.ImageURL
	6,  // 6: plugin.ImagePart.binary:type_name -> plugin.BinaryImage
	9,  // 7: plugin.ExecuteResponse.structured_content:type_name -> google.protobuf.Struct
	7,  // 8: plugin.ExecuteResponse.image_parts:type_name -> plugin.ImagePart
	10, // 9: plugin.PluginService.Init:input_type -> google.protobuf.Empty
	10, // 10: plugin.PluginService.Name:input_type -> google.protobuf.Empty
	10, // 11: plugin.PluginService.Description:input_type -> google.protobuf.Empty
	10, // 12: plugin.PluginService.Properties:input_type -> google.protobuf.Empty
	4,  // 13: plugin.PluginService.Execute:input_type -> plugin.ExecuteRequest
	10, // 14: plugin.PluginService.Ping:input_type -> google.protobuf.Empty
	10, // 15: plugin.PluginService.Init:output_type -> google.protobuf.Empty
	0,  // 16: plugin.PluginService.Name:output_type -> plugin.NameResponse
	1,  // 17: plugin.PluginService.Description:output_type -> plugin.DescriptionResponse
	3,  // 18: plugin.PluginService.Properties:output_type -> plugin.PropertiesResponse
	8,  // 19: plugin.PluginService.Execute:output_type -> plugin.ExecuteResponse
	10, // 20: plugin.PluginService.Ping:output_type -> google.protobuf.Empty
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_agent_toolplugin_pb_plugin_proto_init() }
func file_agent_toolplugin_pb_plugin_proto_init() {
	if File_agent_toolplugin_pb_plugin_proto != nil {
		return
	}
	file_agent_toolplugin_pb_plugin_proto_msgTypes[7].OneofWrappers = []any{
		(*ImagePart_ImageUrl)(nil),
		(*ImagePart_Binary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_toolplugin_pb_plugin_proto_rawDesc), len(file_agent_toolplugin_pb_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_toolplugin_pb_plugin_proto_goTypes,
		DependencyIndexes: file_agent_toolplugin_pb_plugin_proto_depIdxs,
		MessageInfos:      file_agent_toolplugin_pb_plugin_proto_msgTypes,
	}.Build()
	File_agent_toolplugin_pb_plugin_proto = out.File
	file_agent_toolplugin_pb_plugin_proto_goTypes = nil
	file_agent_toolplugin_pb_plugin_proto_depIdxs = nil
}
